### ISSUE TITLE
Applescripts not working

### ISSUE THREAD

**Issue by funkypenguin** [martakostova/pomodoro#19]
Hey,

Not sure if I'm doing something wrong.. I'm using these simple applescripts to change my Adium status based on timers:

https://github.com/johnhampton/PomoScripts

The scripts work fine when executed from the CLI, using osascript, but don't work at all in Timer.

When I try and execute them from the "Timer Scripting Helper", I get the error below popping up:

```
"System Events got an error: Application isn't running"
```

Do I need to adjust the scripts to make them work in Timer?

Thanks!
David

**Comment by simpsonjulian** [comment]
+1

**Comment by ruggibrante** [comment]
+1

**Comment by martakostova** [comment]
Guys, I would be very happy If I could help with this, but the issue is not in the app itself.
The problem is that all apps in the App Store are required to be in Sandbox mode. This means that they can access only their own folder and do not know or access anything else. 
This is the way Apple keep secure your Mac. If the app is not in that sandbox mode, this means that it has access to all your Mac.
The only way you can use Apple Scripts in this app like before is to build the app yourself and remove the sandboxing. Read the README.txt for instructions.

**Comment by tplesnar** [comment]
I bought the MAS version and since the version number is higher, I prefer to use this one.

Removing the sandboxing from a packaged app is simple:

`cd /Applications/Timer.app/Contents/MacOS; open .`

Then open `Timer` in hexfiend and search for the "app-sandbox" and replace `true` by `fals` __missing e isn't a typo__. Save. Enjoy.

Script working in the edited version allowing to set/unset doNotDisturb in Notification center
```set tDate to do shell script "date -u \"+%Y-%m-%dT%TZ\"" --  the current date in UTC time. --> "2016-04-04T17:03:04Z"
do shell script "defaults -currentHost write com.apple.notificationcenterui doNotDisturb -bool TRUE; defaults -currentHost write com.apple.notificationcenterui doNotDisturbDate -date " & tDate & "; osascript -e 'quit application \"NotificationCenter\" ' && killall usernoted"```
